### ISSUE TITLE
change mat_samp_id in batch info and ENA

### ISSUE THREAD

**Issue by kmexter** [emo-bon/observatory-hcmr-1-crate#15]
The batch info files in sequencing_data wth the material sample IDs will need changing as we have changed the material sample IDs
Those IDs as added to ENA already will need changing also

To change:
- we swapped filter size low and up so that changes in the ID
- we changed blank to blank_1
- we will add a new field to the IDs for sediments (not yet done)

--> @kmexter will do the batch info part, @cpavloud should do the ENA part 

But I am going to wait until the sediment IDs have been changed

**Comment by cpavloud** [comment]
This is also related to https://github.com/emo-bon/sequencing-data/issues/10
(Working on it now)

**Comment by cpavloud** [comment]
The ENA part is done. And .csv files in the sequencing_data repo are corrected. I think we can close this issue?

**Comment by kmexter** [comment]
yup
